image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/quamotion/appium-docker-ios

stages:
#  - build
  - test
  - history
  - allure
  - pages
  - deploy

variables:
  MAVEN_REPO_LOCAL: $CI_PROJECT_DIR/.m2/repository
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$MAVEN_REPO_LOCAL -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-X -U --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: /certs
  HOST_SOURCES: /opt/sources
  M2_REPO: $HOST_SOURCES/.m2/repository
  BUILDS: /opt/total-latest


#test
#include:
#  - project: DEPR/ias_tarif/gitlab-ci
#    file: gitlab-ci-dump.yml
#  - project: DEPR/ias_tarif/gitlab-ci
#    file: gitlab-ci-restore.yml


test-job:
  allow_failure: true
  stage: test
#  image: node:latest
#  tags:
#    - test
#  before_script:
#    - appium --address 127.0.0.1 --port 4723
  script:
    - curl "https://nodejs.org/dist/latest/node-${VERSION:-$(wget -qO- https://nodejs.org/dist/latest/ | sed -nE 's|.*>node-(.*)\.pkg</a>.*|\1|p')}.pkg" > "$HOME/Downloads/node-latest.pkg" && sudo installer -store -pkg "$HOME/Downloads/node-latest.pkg" -target "/"
    - PROFILE="all-tests"
    - echo $PROFILE
    - mvn -P$PROFILE clean install -B -e -Dmaven.repo.local=$M2_REPO
  artifacts:
    when: always
    paths:
      - ventureSurf-UI/target/allure-results
    expire_in: 1 hour
    reports:
      junit:
        - ventureSurf-UI/target/surefire-reports/TEST-*.xml
        - ventureSurf-UI/target/failsafe-reports/TEST-*.xml
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - when: never

history-job:
  stage: history
  allow_failure: true
  needs:
    - test-job
  image: storytel/alpine-bash-curl
#  tags:
#    - test
  script:
    - curl --location --output artifacts.zip --header "PRIVATE-TOKEN:YRzNZC9zdY5xXPSQz1z_" "https://gitlab.croc.ru/api/v4/projects/2997/jobs/artifacts/master/download?job=pages"
    - apk add unzip
    - ls -la
    - unzip artifacts.zip
    - chmod -R 777 public
    - cp -r ./public/history ./ventureSurf-UI/target/allure-results
  artifacts:
    when: always
    paths:
      - artifacts*.zip
      - ventureSurf-UI/target/allure-results # Сохраняем данные
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - when: never

allure:
  stage: allure
  image: frankescobar/allure-docker-service
#  tags:
#    - test
  script:
    - allure generate -c ventureSurf-UI/target/allure-results -o ./allure-report
  artifacts:
    paths:
      - ./allure-results
      - ./ventureSurf-UI/target/allure-report
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - when: never

pages:
  stage: pages
#  tags:
#    - test
  script:
    - mkdir public
    - mv ./allure-report/* public
  artifacts:
    when: always
    paths:
      - public
    expire_in: 30 days
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
      when: always
    - when: never